data:
  type: hf_mlm
  source:
    path: carlesoctav/skripsi_UI_membership_30K
    split: train
  processing:
    tokenizer_name: bert-base-uncased
    column_name: id_title
    max_length: 512
    mlm_probability: 0.15
  dataloader:
    batch_size: 64
    partition_spec: [dp]
    shuffle: true
    worker_count: 4
    worker_buffer_size: 2

num_train_steps: 400
gradient_accumulation_steps: 1
seed: 42
mesh_shape: [4]
mesh_axis_names: [dp]

model:
  type: bert
  task: mlm
  vocab_size: 30522
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  max_position_embeddings: 512
  type_vocab_size: 2
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  use_scan: True

optimizer:
  type: adam
  lr: 5.0e-5
  lr_schedule: cosine
  warmup: 0.1
  lr_decay: 0.9
  cycle_length: 1.0
  weight_decay: 0.01

loss_function:
  type: mlm

tracker : null

# tracker:
#   type: wandb
#   project: benchmark
#   entity: your-entity
#   name: local_debug
#   tags: ["benchmark", "bert"]
