type: bert
task: mlm
vocab_size: 30522
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
max_position_embeddings: 512
type_vocab_size: 2
layer_norm_eps: 1.0e-12
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
pad_token_id: 0
initializer_range: 0.02
tie_word_embeddings: true
use_scan: true
_attn_implementation: eager
